services:
  - type: web
    name: bridge-talk-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node dist/server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: OPENAI_API_KEY
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
    autoDeploy: true
